language: node_js
node_js:
- 10.6.0
branches:
  only:
  - development
  - master
before_script:
- npm install -g firebase-tools
- npm install -g @angular/cli
script:
- npm run ci
before_deploy:
- cd dist/processpuzzle-doc-lib
deploy:
  provider: npm
  email: zsolt.zsuffa@gmail.com
  skip_cleanup: true
  on:
    branch: development
    tags: false
  api_key:
    secure: h6Zvcc1GVjnml3kSlFmkrtYYOo7ZbML29y8QZZBJJ0RF3Vhc/QpiExA0SBrUf2lqx0c20OMHTzTThvTPCX7R6sc5TB/rCCPtrEYKonDjyS2RTjVgF2MJLYz5fZr9jeHSPB/rIZue3DA0q9zD6pnM3nYvvf1TgOujXJXWRqR/CkVFpzXr2U7Z1//eT+bRfEDXbAeuDHgrEdzdDgPm5lvuurdIkmwgSZg1Bevop59yxjxy8DOX40uJkJCPmbKvluyOtVwVB83Ksk3hALpIUS0Y/ynAo3ycXnrbKM1tKwgPPTCaYVVgL+Gm2kY7cJ5hVj7+J7dr+B3sCsoOyL1Q+uRgnioe7eJKaPEz+YCqNRewnYNxVuvs2nIzZsrguLH+YOQ4LcDcQdvE4yOFEKnmW/6d0iMK2PE7yUghpHMFq4N34s8z6K5XbnfWsNHjwBkPJQKTTqZtrTXk4hzdFgszVfaG1DHqYmG9WWCXDBzzMrn7T2SBE9LjMmJRpyNxCwIUkPqViJZLHn92FZsQ9Akt4fIvNv4Zq0WDUhrsM4JamWR4fsN4CmFRpsdgeBbXz1sT0tINTZ3EMujLyO6gtIjPlmoJOTgZhLiuQbVT64LLzeRiM9MyvfrIA+pzYTSDXpplwmkSaLlUM4JYWng0YSDKdSiMBa1Eu4di5g+BS3szS1p5f1Y=
notifications:
  email:
    on_failure: change
    on_success: change
